/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pabloloaiza.estudiocasopractico2;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Loaiza
 */
public class NuevoDiccionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoDiccionario.class.getName());

    /**
     * Creates new form NuevoDiccionario
     */
    public NuevoDiccionario() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FieldNuevoTermino = new javax.swing.JTextField();
        PanelNuevaDescripcion = new javax.swing.JScrollPane();
        FieldNuevaDescripcion = new javax.swing.JTextArea();
        BotonGuardarTermino = new javax.swing.JButton();
        BotonGuardarDiccionario = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FieldNuevoTermino.addActionListener(this::FieldNuevoTerminoActionPerformed);

        FieldNuevaDescripcion.setColumns(20);
        FieldNuevaDescripcion.setRows(5);
        PanelNuevaDescripcion.setViewportView(FieldNuevaDescripcion);

        BotonGuardarTermino.setText("Guardar Termino");
        BotonGuardarTermino.addActionListener(this::BotonGuardarTerminoActionPerformed);

        BotonGuardarDiccionario.setText("Guardar Diccionario");
        BotonGuardarDiccionario.addActionListener(this::BotonGuardarDiccionarioActionPerformed);

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(this::BotonVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelNuevaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(BotonGuardarTermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonGuardarDiccionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonVolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FieldNuevoTermino, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(FieldNuevoTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelNuevaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonGuardarTermino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonGuardarDiccionario)
                .addGap(18, 18, 18)
                .addComponent(BotonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNuevoTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNuevoTerminoActionPerformed
        
    }//GEN-LAST:event_FieldNuevoTerminoActionPerformed

    ArrayList<Termino> NuevoSetTerminos = new ArrayList<>();

    private void BotonGuardarTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarTerminoActionPerformed
        String nuevoTermino = FieldNuevoTermino.getText();
        String nuevaDescription = FieldNuevaDescripcion.getText();
        boolean existe = false;
        
        //Antes de agregar el término, se revisa si ya eiste.
        for(Termino termino: NuevoSetTerminos){
           if(termino.getTermino().equals(nuevoTermino)){
               existe = true;
               break;
           }
        }
        
        if (!existe) {
            NuevoSetTerminos.add(new Termino(nuevoTermino, nuevaDescription));
            FieldNuevoTermino.setText("");
            FieldNuevaDescripcion.setText("");
            JOptionPane.showMessageDialog(
                    null,
                    "Termino guardado correctamente",
                    "Notificacion",
                    JOptionPane.INFORMATION_MESSAGE
            );
            //Falla con "no compatible"
            //Collections.sort(NuevoSetTerminos);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "El termino ya existe en el diccionario",
                    "Notificacion",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_BotonGuardarTerminoActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonGuardarDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarDiccionarioActionPerformed
        Diccionario diccionarioGuardar = new Diccionario(NuevoSetTerminos);
        Diccionario.EscribirDiccionario(diccionarioGuardar);
    }//GEN-LAST:event_BotonGuardarDiccionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NuevoDiccionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardarDiccionario;
    private javax.swing.JButton BotonGuardarTermino;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTextArea FieldNuevaDescripcion;
    private javax.swing.JTextField FieldNuevoTermino;
    private javax.swing.JScrollPane PanelNuevaDescripcion;
    // End of variables declaration//GEN-END:variables
}
