/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pabloloaiza.estudiocasopractico2;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Loaiza
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FieldBuscador = new javax.swing.JTextField();
        BotonBuscador = new javax.swing.JButton();
        ResultadoBuscador = new javax.swing.JLabel();
        BarraOpciones = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        OpcionNuevoDiccionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FieldBuscador.addActionListener(this::FieldBuscadorActionPerformed);

        BotonBuscador.setText("Buscar");
        BotonBuscador.addActionListener(this::BotonBuscadorActionPerformed);

        MenuOpciones.setText("Opciones");

        OpcionNuevoDiccionario.setText("Nuevo Diccionario");
        OpcionNuevoDiccionario.addActionListener(this::OpcionNuevoDiccionarioActionPerformed);
        MenuOpciones.add(OpcionNuevoDiccionario);

        BarraOpciones.add(MenuOpciones);

        setJMenuBar(BarraOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultadoBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FieldBuscador)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(BotonBuscador)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(FieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonBuscador)
                .addGap(18, 18, 18)
                .addComponent(ResultadoBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Termino> terminosDiccionario;
    
    private void BotonBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscadorActionPerformed
        Diccionario diccionario = new Diccionario(terminosDiccionario);
        
        //Hasta aqui, aun no se puede buscar en el archivo serializado.
        //diccionario = diccionario.getTerminiosdiccionario();
        String terminoBuscar = FieldBuscador.getSelectedText();

        boolean existe = false;
        for (Termino termino : diccionario.getTerminiosdiccionario()) {
            if (termino.getTermino().equals(terminoBuscar)) {
                existe = true;
                JOptionPane.showMessageDialog(
                        null,
                        "Descripción: " + termino.getDescripcion(),
                        "Notificacion",
                        JOptionPane.INFORMATION_MESSAGE
                );
                ResultadoBuscador.setText("Descripción: " + termino.getDescripcion());
                break;
            }
        }

        if (existe) {
            System.out.println("Debería imprimir aquí o dentro del for?");
        } else {
            System.out.println("El termino no existe en el diccionario");
        }
        System.out.println(Arrays.asList(diccionario));
    }//GEN-LAST:event_BotonBuscadorActionPerformed

    private void FieldBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBuscadorActionPerformed

    private void OpcionNuevoDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionNuevoDiccionarioActionPerformed
        new NuevoDiccionario().setVisible(true);
    }//GEN-LAST:event_OpcionNuevoDiccionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraOpciones;
    private javax.swing.JButton BotonBuscador;
    private javax.swing.JTextField FieldBuscador;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JMenuItem OpcionNuevoDiccionario;
    private javax.swing.JLabel ResultadoBuscador;
    // End of variables declaration//GEN-END:variables
}
